name: jiaowuxitong_app
description: A new Flutter project for JiaoWuXiTong.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  dio_cookie_manager: ^3.0.0
  cookie_jar: ^4.0.0
  path_provider: ^2.1.1
  html: ^0.15.4
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  intl: ^0.18.1
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
